### PR TITLE
updated flavors for BM

### PR DESCRIPTION
**Pull request by BerndKue**

### CODE REVIEW

**Comment by BerndKue** [comment]
@databus23 Please check if this is ok.

**Comment by databus23** [comment]
@BerndKue I'm not sure what to check here. This is outside my area of expertise @bozinsky maybe?

**Comment by BerndKue** [comment]
sorry, I got the wrong Fabian. :(

**Comment by bozinsky** [comment]
@BerndKue comparing to the reference doc we have is correct. @fwiesel do you have any remarks?

**Comment by fwiesel** [comment]
Looks good to me too.

**Pull request merged**
