### PR TITLE
[rabbitmq] adds additional prop for persistence value

### PR DESCRIPTION
**Pull request by stefanhipfel**

### CODE REVIEW

**Comment by stefanhipfel** [comment]
Needed to remove persistence in globals.value for each region!

otherwise we would also overwrite rabbit notification persistence values, e.g.:
https://github.wdf.sap.corp/cc/secrets/blob/master/staging/values/keystone.yaml#L116

**Review by fwiesel — CHANGES_REQUESTED** [review]
Sorry, but for me it doesn't make sense.
You are breaking abstraction of the rabbitmq chart.

It was correct before. There is a rabbitmq chart, and you can enable / disable persistence.

That we use it for rpc should not matter to this chart.

**Comment by stefanhipfel** [comment]
the keystone rabbit however was changed...
https://ci.global.cloud.sap/teams/main/pipelines/openstack-keystone/jobs/staging-diff/builds/66#L5b6dbb21:112

so i cannot use the globals

**Comment by fwiesel** [comment]
I don't see, how the two relate with one another.

You renamed a chart-local variable from `.persistence.enabled` to `.rabbit_rpc.persistence.enabled`.

The same way you can disable persistence by changing the variable `.rabbit_rpc.persistence.enabled`, you can change it by setting the variable `.persistence.enabled`.

**Pull request closed without merging**
